### ISSUE TITLE
Looking for a new maintainer for this project

### ISSUE THREAD

**Issue by romix** [altoo-ag/akka-kryo-serialization#143]
Hi everyone!

I haven't been maintaining this project for years as I do not use Java or Scala frequently these days. Sorry for any inconvenience it may have caused!

But when I look at issues and PRs it seems like some people are still using it. 

Therefore I'd like to ask if anyone is interested in taking over the maintenance of this project? I'd gladly hand it over to a new maintainer.

Please respond if you are interested.

**Comment by danischroeter** [comment]
Hi Romix

Thx a lot for the effort on the project! We are actively using it and since we are interested in a healthy/up to date state would take over maintenance of the project.

Since we would like to go through the open PR's such as the scala2.13 support etc. we think it would be easiest if you could transfer the project to our company github account. This way we can easily apply the existing PR's and can give permissions to developers. The account would be https://github.com/altoo-ag (see https://help.github.com/en/articles/transferring-a-repository)

**Comment by romix** [comment]
@danischroeter Thanks a lot of taking over the maintenance of this project! I'd be happy to transfer the project to your company!

**Comment by romix** [comment]
@danischroeter I just tried to transfer it to the account "altoo-ag" and I get an error "You don’t have the permission to create public repositories on altoo-ag". Please let me know how to proceed. If you'd like to avoid posting some details here, please contact me privately.

**Comment by danischroeter** [comment]
hi @romix 
Sorry about that. There was a part I did not know about repo transfers - there are different permissions needed for organization accounts...

> To transfer repositories to an organization, you must have repository creation permissions in the receiving organization.

Could you transfer to my personal account (danischroeter) pls? From there i can then do the final transfer...

**Comment by romix** [comment]
> Could you transfer to my personal account (danischroeter) pls? From there i can then do the final transfer...

Done!

**Comment by danischroeter** [comment]
Now it worked :+1: 
We are looking forward to continue the great work you started. Thx a lot!
