### ISSUE TITLE
Kryo failed to serialize message

### ISSUE THREAD

**Issue by idar** [altoo-ag/akka-kryo-serialization#24]
I am getting some serialization error only in our production environment, and i can't figure out what message causes it. (Too high load to log all messages). 

Is there a way to log which class caused this error?

Exception:
akka.remote.EndpointException: Failed to write message to the transport
Caused by: java.lang.Exception: Couldn't acquire object in 5000 milliseconds.
        at com.romix.akka.serialization.kryo.ObjectPool.block(KryoSerializer.scala:347)
        at com.romix.akka.serialization.kryo.ObjectPool.createOrBlock(KryoSerializer.scala:331)
        at com.romix.akka.serialization.kryo.ObjectPool.fetch(KryoSerializer.scala:317)
        at com.romix.akka.serialization.kryo.KryoSerializer.getSerializer(KryoSerializer.scala:158)
        at com.romix.akka.serialization.kryo.KryoSerializer.toBinary(KryoSerializer.scala:138)
        at akka.remote.MessageSerializer$.serialize(MessageSerializer.scala:36)
        at akka.remote.EndpointWriter$$anonfun$akka$remote$EndpointWriter$$serializeMessage$1.apply(Endpoint.scala:643
)
        at akka.remote.EndpointWriter$$anonfun$akka$remote$EndpointWriter$$serializeMessage$1.apply(Endpoint.scala:643
)
        at scala.util.DynamicVariable.withValue(DynamicVariable.scala:57)
        at akka.remote.EndpointWriter.akka$remote$EndpointWriter$$serializeMessage(Endpoint.scala:642)
        at akka.remote.EndpointWriter$$anonfun$7.applyOrElse(Endpoint.scala:530)
        at akka.remote.EndpointWriter$$anonfun$7.applyOrElse(Endpoint.scala:515)
        at scala.runtime.AbstractPartialFunction.apply(AbstractPartialFunction.scala:33)
        at akka.actor.FSM$class.processEvent(FSM.scala:595)

**Comment by guidomedina** [comment]
I started using this extension today, it is working properly on a green field project, but it would be nicer to elaborate more on the configuration options of Kryo specifically for Akka, parameters like:
```
      serializer-pool-size = 16
      buffer-size = 4096
```

For example you say 16 is very low, but what's your criteria to come up with a number, I for one tend to try multiples of 2 like 32, 64, 128, etc, but those are just numbers with no context, it would be nice to come up with an approximation formula like `N * (N - 1) x CPUs` for worst scenario.

Each node is an `Actor System` where for `N nodes` each can potentially communicate with `N - 1`

**Comment by romix** [comment]
Well, the buffer size should match the typical size of your serialized messages.

When it comes to the serializer-pool-size, then the idea is to have enough elements in a buffer, so that you can always process all your simultaneous in-flight messages. I would imagine that having serializer-pool-size at least as low as the max number of actors on your machine would guarantee that no actor has to wait for a serializer to become available. But this is a very pessimistic estimate of course. In many cases a much lower figure would be OK.

**Comment by guidomedina** [comment]
Or could it as many concurrent actors are sending messages? Taking into account that context switches will cause many actors to wait to share CPU, so if you have 8 CPU, chances are you have at least 64 concurrent active actors?

I'm just trying as you know to come up with the closest way to estimate these numbers.

**Comment by guidomedina** [comment]
Or the actor system fork-join dispatcher max parallelism value? Which by default I think it is 64?

**Comment by romix** [comment]
First a disclaimer: I'm more involved in Kryo development rather than in Akka development. 
But as I said, the basic idea is to make sure that any of the actors running at the same time (i.e. simultaneously) and using Kryo serializers should be able to get its own instance of a serializer. 
Which means, IMHO: check the configuration parameters you use to control the max number of simultaneous actors and use the same max number. I guess this would be the number of a thread pool for your actor dispatcher, i.e. for a fork-join dispatcher, because this seems to be the max number of actors simultaneously processing messages at any moment in time.

**Comment by guidomedina** [comment]
Thanks for your response, I just wanted to learn from the creator(s) of the bridge between Akka and Kryo, nothing more, I never implied that you were responsible in any way for the Akka side of the equation, I assumed you knew all that information better than me because I have been using Akka for 3 weeks and discovered this extension 2 days ago, maybe I need to go back a re-read the documentation or maybe the documentation need to be more explicit, either way, I just wanted to know more so thank you very much for the quick response, truly appreciated.

**Comment by luben** [comment]
Hi Romix,

I see that there is a built in object pool in Kryo 3.0 that we are using now. I have built a serializer based on akka-kryo-serialization (not for akka messages, for some on-disk format) that uses the kryo pool and it looks good.

Do you think it is worth to drop our pool implementation and use the kryo provided pool?

**Comment by hepin1989** [comment]
even i am using my own implement,i think the current kryo pool implement is ok.and the size ,should be bigger if you have a dedicated dispatcher fow the remote io.it is a concurrentqueue

**Comment by romix** [comment]
@luben I have nothing against dropping our pool implementation and using the kryo provided pool. If the performance does not suffer do to this change, I'm OK with it. Please submit a PR.

**Comment by guidomedina** [comment]
@luben I just took a look at the current `ObjectPool` which is based on an `ArrayBlockingQueue`, I wonder if it isn't better to replace it by a LMAX disruptor pool?, it sure will greatly increase performance for low latency, many small messages like applications, I'm not a Scala developer, I know I can build it for Java but unfortunately I can't give you a pull request for Scala, so here is something I found that might help, a Scala LMAX Disruptor Queue: https://gist.github.com/tobiassvn/6782639

**Comment by luben** [comment]
@guidomedina Part of my motivation was to decrease the complexity - if Kryo provides an object pool why don't we delegate the task to Kryo instead of supporting our own implementation. We had developed our own pool because there was no pool in previous versions of Kryo. I will look for your proposal for using LMAX Disruptor Queue. Thanks for the proposal.
