### ISSUE TITLE
can register "scala.collection.immutable.Map$Map1"

### ISSUE THREAD

**Issue by nefilim** [altoo-ag/akka-kryo-serialization#25]
Implicitly registered class with id: scala.collection.immutable.Map$Map1=1962562276

This happens when I have a 

``` scala
case class Stuff(map: Map[String, Map[String, String]]) 
```

and try to serialize a literal like:

``` scala
Stuff(
   Map("group1" -> Map(("key1" -> "value1")))
)
```

I've tried everything I could think of including:

```
kryo.register(Map.empty[String, Map[String, String]].getClass)
kryo.register(Map[String, Map[String, String]]().getClass)
kryo.register(Map.getClass)
kryo.register(classOf[scala.collection.immutable.Map[_, _]])
kryo.register(classOf[scala.collection.immutable.DefaultMap[_, _]])
```

with no luck :(

**Comment by jducoeur** [comment]
Don't have a self-contained test case (the relevant code isn't even on GitHub yet), but I'm hitting a variant of this same problem.  My Akka Persisted entity has:
```
private var fullShards = Set[ShardId](0, 1, 2, 3)
```
I'm persisting it in this message:
```
case class ShardSnapshot(@KryoTag(1) fullShards:Set[ShardId], @KryoTag(2) shardAssignments:Map[ActorPath, ShardId]) extends UseKryo
```
It turns out that the literal `Set` winds up getting instantiated in Scala as `scala.collection.immutable.Set.Set4`, a special optimized version of `Set` that is contained in its companion.  So it isn't actually implemented as a HashSet, it's this special little thing, which apparently has to be separately registered.

I'm going to try working around it by declaring the object to be explicitly a HashSet (which will hopefully allow me to just register HashSet), but I'm still trying to puzzle out if there's a better way to do this.  

Am I correct that Kryo has no concept of "use this registration for all subclasses of T"?  If so, then this is going to be an ongoing gotcha, I think -- there are a *lot* of subtle hidden subclasses lurking in the collections library.  Indeed, what I'm most concerned about is that `Set` and `Map` both have "empty" variants that are entirely private -- so I'm sure it's even *possible* to register them...

**Comment by jducoeur** [comment]
Actually, I should be clear: this might only be a problem if explicit registration is required.  It took me a while to grok that `addDefaultSerializer()` wasn't relevant, because I want to be hard-assed about requiring all of the registrations to be spelled out.

(I'm using this for persistence, so I have to be *extremely* careful about it.  Not sure how many people have tried that yet, but I like Kryo's in-code approach to data description more than protobuf's externalized view...)

**Comment by jasongoodwin** [comment]
Does resolve-subclasses = true fix this now? 
jducoeur, I'd really like to talk to you about your experiences sometime. jason.goodwin at redelastic dot com - maybe you could email me? I saw your whitepaper and am doing a deep dive on kryo right now.

**Comment by jducoeur** [comment]
Yes, the SubclassResolver was written specifically to fix this problem.  I'll drop you an email, but the short version is that I'm jducoeur on approximately every major system on the Internet...

**Comment by wangyum** [comment]
Try `kryo.register(Class.forName("scala.collection.immutable.Map$Map1"))`

**Comment by jducoeur** [comment]
That's true, but only scratches the surface of the problem.  There turn out to be a host of these specialized little classes -- IIRC, registering `Set` properly requires *six* different classes, including at least one that is defined inside of a closure.  (I don't recall if I ever puzzled out a syntax to be able to register that.)  I eventually decided that introducing `SubclassResolver` was easier than dealing with this ongoing headache...
